/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './footer.component';
const styles_FooterComponent:any[] = ['hr[_ngcontent-%COMP%] {\n    border: 0;\n    height: 1px;\n    background: #333;\n    background-image: linear-gradient(to right, #ccc, #333, #ccc);\n}'];
export const RenderType_FooterComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 0,
  styles: styles_FooterComponent,
  data: {}
}
);
export function View_FooterComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n'])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),18,'div',[
      [
        'class',
        'row'
      ]
      ,
      [
        'style',
        'text-align:center;'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n  '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),15,'div',[[
        'class',
        'col-md-12'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),0,'hr',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Created by © Nikhil Shende'])),
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Computer Science Graduate Student at University of Texas at Arlington'])),
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Email: nikhil.shende@mavs.uta.edu'])),
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Phone: +1 682-256-8542 '])),
    (l()(),import0.ɵted((null as any),['\n  '])),
    (l()(),import0.ɵted((null as any),['\n']))
  ]
  ,(null as any),(null as any));
}
function View_FooterComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-footer',([] as any[]),(null as any),(null as any),(null as any),View_FooterComponent_0,RenderType_FooterComponent)),
    import0.ɵdid(49152,(null as any),0,import1.FooterComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const FooterComponentNgFactory:import0.ComponentFactory<import1.FooterComponent> = import0.ɵccf('app-footer',import1.FooterComponent,View_FooterComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvTmlraGlsL0Rlc2t0b3AvQW5ndWxhckFwcHMveWVscGFwdC9hc3NldHMvYXBwL2Zvb3Rlci9mb290ZXIuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL05pa2hpbC9EZXNrdG9wL0FuZ3VsYXJBcHBzL3llbHBhcHQvYXNzZXRzL2FwcC9mb290ZXIvZm9vdGVyLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL05pa2hpbC9EZXNrdG9wL0FuZ3VsYXJBcHBzL3llbHBhcHQvYXNzZXRzL2FwcC9mb290ZXIvZm9vdGVyLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvTmlraGlsL0Rlc2t0b3AvQW5ndWxhckFwcHMveWVscGFwdC9hc3NldHMvYXBwL2Zvb3Rlci9mb290ZXIuY29tcG9uZW50LnRzLkZvb3RlckNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxzdHlsZT5cclxuICAgIGhyIHtcclxuICAgIGJvcmRlcjogMDtcclxuICAgIGhlaWdodDogMXB4O1xyXG4gICAgYmFja2dyb3VuZDogIzMzMztcclxuICAgIGJhY2tncm91bmQtaW1hZ2U6IGxpbmVhci1ncmFkaWVudCh0byByaWdodCwgI2NjYywgIzMzMywgI2NjYyk7XHJcbn1cclxuICAgIDwvc3R5bGU+XHJcbjxkaXYgY2xhc3M9XCJyb3dcIiBzdHlsZT1cInRleHQtYWxpZ246Y2VudGVyO1wiPlxyXG4gIDxkaXYgY2xhc3M9XCJjb2wtbWQtMTJcIj5cclxuICAgIDxocj5cclxuICAgIDxwPkNyZWF0ZWQgYnkgJmNvcHk7IE5pa2hpbCBTaGVuZGU8L3A+XHJcbiAgICA8cD5Db21wdXRlciBTY2llbmNlIEdyYWR1YXRlIFN0dWRlbnQgYXQgVW5pdmVyc2l0eSBvZiBUZXhhcyBhdCBBcmxpbmd0b248L3A+XHJcbiAgICA8cD5FbWFpbDogbmlraGlsLnNoZW5kZUBtYXZzLnV0YS5lZHU8L3A+XHJcbiAgICA8cD5QaG9uZTogKzEgNjgyLTI1Ni04NTQyIDwvcD5cclxuICA8L2Rpdj5cclxuPC9kaXY+IiwiPGFwcC1mb290ZXI+PC9hcHAtZm9vdGVyPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNPWTtJQUNaO01BQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO01BQUE7O0lBQUE7S0FBQTtJQUE0QztNQUMxQztRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQXVCO0lBQ3JCO0lBQUk7SUFDSjtJQUFHO0lBQW1DO0lBQ3RDO0lBQUc7SUFBeUU7SUFDNUU7SUFBRztJQUFxQztJQUN4QztJQUFHO0lBQTJCO0lBQzFCOzs7Ozs7SUNmUjtnQkFBQTs7OzsifQ==
