/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../comment/comment.component.ngfactory';
import * as import2 from '../comment/comment.component';
import * as import3 from '@angular/common';
import * as import4 from './comment-list.component';
import * as import5 from '../comment.service';
const styles_CommentListComponent:any[] = ([] as any[]);
export const RenderType_CommentListComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_CommentListComponent,
  data: {}
}
);
function View_CommentListComponent_1(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-comment',([] as any[]),(null as any),(null as any),(null as any),import1.View_CommentComponent_0,import1.RenderType_CommentComponent)),
    import0.ɵdid(49152,(null as any),0,import2.CommentComponent,([] as any[]),{
      comment: [
        0,
        'comment'
      ]
      ,
      index: [
        1,
        'index'
      ]

    }
    ,(null as any))
  ]
  ,(ck,v) => {
    const currVal_0:any = v.context.$implicit;
    const currVal_1:any = v.context.index;
    ck(v,1,0,currVal_0,currVal_1);
  },(null as any));
}
export function View_CommentListComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵand(16777216,(null as any),(null as any),1,(null as any),View_CommentListComponent_1)),
    import0.ɵdid(802816,(null as any),0,import3.NgForOf,[
      import0.ViewContainerRef,
      import0.TemplateRef,
      import0.IterableDiffers
    ]
      ,{ngForOf: [
        0,
        'ngForOf'
      ]
    },(null as any))
  ]
  ,(ck,v) => {
    var co:import4.CommentListComponent = v.component;
    const currVal_0:any = co.comments;
    ck(v,1,0,currVal_0);
  },(null as any));
}
function View_CommentListComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-comment-list',([] as any[]),(null as any),(null as any),(null as any),View_CommentListComponent_0,RenderType_CommentListComponent)),
    import0.ɵdid(114688,(null as any),0,import4.CommentListComponent,[import5.CommentService],(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const CommentListComponentNgFactory:import0.ComponentFactory<import4.CommentListComponent> = import0.ɵccf('app-comment-list',import4.CommentListComponent,View_CommentListComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvTmlraGlsL0Rlc2t0b3AvQW5ndWxhckFwcHMveWVscGFwdC9hc3NldHMvYXBwL2NvbW1lbnRzL2NvbW1lbnQtbGlzdC9jb21tZW50LWxpc3QuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL05pa2hpbC9EZXNrdG9wL0FuZ3VsYXJBcHBzL3llbHBhcHQvYXNzZXRzL2FwcC9jb21tZW50cy9jb21tZW50LWxpc3QvY29tbWVudC1saXN0LmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL05pa2hpbC9EZXNrdG9wL0FuZ3VsYXJBcHBzL3llbHBhcHQvYXNzZXRzL2FwcC9jb21tZW50cy9jb21tZW50LWxpc3QvY29tbWVudC1saXN0LmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvTmlraGlsL0Rlc2t0b3AvQW5ndWxhckFwcHMveWVscGFwdC9hc3NldHMvYXBwL2NvbW1lbnRzL2NvbW1lbnQtbGlzdC9jb21tZW50LWxpc3QuY29tcG9uZW50LnRzLkNvbW1lbnRMaXN0Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGFwcC1jb21tZW50ICpuZ0Zvcj1cImxldCBjb21tZW50RWwgb2YgY29tbWVudHM7bGV0IGk9aW5kZXg7XCJcclxuICAgIFtjb21tZW50XT1cImNvbW1lbnRFbFwiIFtpbmRleF09XCJpXCI+PC9hcHAtY29tbWVudD4iLCI8YXBwLWNvbW1lbnQtbGlzdD48L2FwcC1jb21tZW50LWxpc3Q+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtnQkFBQTtNQUFBO1FBQUE7UUFBQTtNQUFBOztNQUFBO1FBQUE7UUFBQTtNQUFBOztJQUFBO0tBQUE7OztJQUNJO0lBQXNCO0lBRDFCLFNBQ0ksVUFBc0IsU0FEMUI7Ozs7O0lBQUE7Z0JBQUE7Ozs7SUFBQTtPQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7Ozs7SUFBYTtJQUFiLFNBQWEsU0FBYjs7Ozs7SUNBQTtnQkFBQTs7O0lBQUE7OzsifQ==
