/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './comment-page.component';
const styles_CommentPageComponent:any[] = ([] as any[]);
export const RenderType_CommentPageComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_CommentPageComponent,
  data: {}
}
);
export function View_CommentPageComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,([] as any[]),(null as any),(null as any));
}
function View_CommentPageComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-comment-page',([] as any[]),(null as any),(null as any),(null as any),View_CommentPageComponent_0,RenderType_CommentPageComponent)),
    import0.ɵdid(49152,(null as any),0,import1.CommentPageComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const CommentPageComponentNgFactory:import0.ComponentFactory<import1.CommentPageComponent> = import0.ɵccf('app-comment-page',import1.CommentPageComponent,View_CommentPageComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvTmlraGlsL0Rlc2t0b3AvQW5ndWxhckFwcHMveWVscGFwdC9hc3NldHMvYXBwL2NvbW1lbnRzL2NvbW1lbnQtcGFnZS9jb21tZW50LXBhZ2UuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL05pa2hpbC9EZXNrdG9wL0FuZ3VsYXJBcHBzL3llbHBhcHQvYXNzZXRzL2FwcC9jb21tZW50cy9jb21tZW50LXBhZ2UvY29tbWVudC1wYWdlLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL05pa2hpbC9EZXNrdG9wL0FuZ3VsYXJBcHBzL3llbHBhcHQvYXNzZXRzL2FwcC9jb21tZW50cy9jb21tZW50LXBhZ2UvY29tbWVudC1wYWdlLmNvbXBvbmVudC50cy5Db21tZW50UGFnZUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxhcHAtY29tbWVudC1wYWdlPjwvYXBwLWNvbW1lbnQtcGFnZT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7Z0JBQUE7Ozs7In0=
