/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './pagenotfound.component';
const styles_PageNotFoundComponent:any[] = ([] as any[]);
export const RenderType_PageNotFoundComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_PageNotFoundComponent,
  data: {}
}
);
export function View_PageNotFoundComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
      (l()(),import0.ɵeld(0,(null as any),(null as any),6,'div',[[
        'class',
        'row'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n    '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),4,'div',[[
        'class',
        'col-md-8'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n        '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Page Not found'])),
    (l()(),import0.ɵted((null as any),['\n']))
  ]
  ,(null as any),(null as any));
}
function View_PageNotFoundComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-pagenotfound',([] as any[]),(null as any),(null as any),(null as any),View_PageNotFoundComponent_0,RenderType_PageNotFoundComponent)),
    import0.ɵdid(49152,(null as any),0,import1.PageNotFoundComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const PageNotFoundComponentNgFactory:import0.ComponentFactory<import1.PageNotFoundComponent> = import0.ɵccf('app-pagenotfound',import1.PageNotFoundComponent,View_PageNotFoundComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvTmlraGlsL0Rlc2t0b3AvQW5ndWxhckFwcHMveWVscGFwdC9hc3NldHMvYXBwL3BhZ2Vub3Rmb3VuZC9wYWdlbm90Zm91bmQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL05pa2hpbC9EZXNrdG9wL0FuZ3VsYXJBcHBzL3llbHBhcHQvYXNzZXRzL2FwcC9wYWdlbm90Zm91bmQvcGFnZW5vdGZvdW5kLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL05pa2hpbC9EZXNrdG9wL0FuZ3VsYXJBcHBzL3llbHBhcHQvYXNzZXRzL2FwcC9wYWdlbm90Zm91bmQvcGFnZW5vdGZvdW5kLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvTmlraGlsL0Rlc2t0b3AvQW5ndWxhckFwcHMveWVscGFwdC9hc3NldHMvYXBwL3BhZ2Vub3Rmb3VuZC9wYWdlbm90Zm91bmQuY29tcG9uZW50LnRzLlBhZ2VOb3RGb3VuZENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9XCJyb3dcIj5cclxuICAgIDxkaXYgY2xhc3M9XCJjb2wtbWQtOFwiPlxyXG4gICAgICAgIDxoMT5QYWdlIE5vdCBmb3VuZDwvaDE+XHJcbjwvZGl2PiIsIjxhcHAtcGFnZW5vdGZvdW5kPjwvYXBwLXBhZ2Vub3Rmb3VuZD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7O01DQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUFpQjtNQUNiO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBc0I7SUFDbEI7SUFBSTtJQUFtQjs7Ozs7O0lDRi9CO2dCQUFBOzs7OyJ9
