/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './auth/header/header.component.ngfactory';
import * as import2 from './auth/header/header.component';
import * as import3 from './auth/auth.service';
import * as import4 from '@angular/router';
import * as import5 from './error/error.component.ngfactory';
import * as import6 from './error/error.component';
import * as import7 from './error/error.service';
import * as import8 from './footer/footer.component.ngfactory';
import * as import9 from './footer/footer.component';
import * as import10 from './app.component';
const styles_AppComponent:any[] = ([] as any[]);
export const RenderType_AppComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_AppComponent,
  data: {}
}
);
export function View_AppComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-header',([] as any[]),(null as any),(null as any),(null as any),import1.View_HeaderComponent_0,import1.RenderType_HeaderComponent)),
    import0.ɵdid(49152,(null as any),0,import2.HeaderComponent,[import3.AuthService],(null as any),(null as any)),
    (l()(),import0.ɵted((null as any),['\n'])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),4,'div',[[
        'class',
        'container'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵeld(16777216,(null as any),(null as any),1,'router-outlet',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    import0.ɵdid(147456,(null as any),0,import4.RouterOutlet,[
      import4.RouterOutletMap,
      import0.ViewContainerRef,
      import0.ComponentFactoryResolver,
      [
        8,
        (null as any)
      ]

    ]
    ,(null as any),(null as any)),
    (l()(),import0.ɵted((null as any),['\n'])),
    (l()(),import0.ɵted((null as any),['\n'])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-error',([] as any[]),(null as any),(null as any),(null as any),import5.View_ErrorComponent_0,import5.RenderType_ErrorComponent)),
    import0.ɵdid(114688,(null as any),0,import6.ErrorComponent,[import7.ErrorService],(null as any),(null as any)),
    (l()(),import0.ɵted((null as any),['\n'])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-footer',([] as any[]),(null as any),(null as any),(null as any),import8.View_FooterComponent_0,import8.RenderType_FooterComponent)),
    import0.ɵdid(49152,(null as any),0,import9.FooterComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,10,0);
  },(null as any));
}
function View_AppComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'my-app',([] as any[]),(null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
    import0.ɵdid(49152,(null as any),0,import10.AppComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const AppComponentNgFactory:import0.ComponentFactory<import10.AppComponent> = import0.ɵccf('my-app',import10.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvTmlraGlsL0Rlc2t0b3AvQW5ndWxhckFwcHMveWVscGFwdC9hc3NldHMvYXBwL2FwcC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvTmlraGlsL0Rlc2t0b3AvQW5ndWxhckFwcHMveWVscGFwdC9hc3NldHMvYXBwL2FwcC5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9OaWtoaWwvRGVza3RvcC9Bbmd1bGFyQXBwcy95ZWxwYXB0L2Fzc2V0cy9hcHAvYXBwLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvTmlraGlsL0Rlc2t0b3AvQW5ndWxhckFwcHMveWVscGFwdC9hc3NldHMvYXBwL2FwcC5jb21wb25lbnQudHMuQXBwQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGFwcC1oZWFkZXI+PC9hcHAtaGVhZGVyPlxyXG48ZGl2IGNsYXNzPVwiY29udGFpbmVyXCI+XHJcbiAgICA8cm91dGVyLW91dGxldD48L3JvdXRlci1vdXRsZXQ+XHJcbjwvZGl2PlxyXG48YXBwLWVycm9yPjwvYXBwLWVycm9yPlxyXG48YXBwLWZvb3Rlcj48L2FwcC1mb290ZXI+IiwiPG15LWFwcD48L215LWFwcD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7Z0JBQUE7SUFBeUI7TUFDekI7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUF1QjtJQUNuQjtnQkFBQTs7OztNQUFBO1FBQUE7UUFBQTtNQUFBOztJQUFBO0tBQUE7SUFBK0I7SUFDN0I7SUFDTjtnQkFBQTtJQUF1QjtJQUN2QjtnQkFBQTs7O0lBREE7Ozs7O0lDSkE7Z0JBQUE7Ozs7In0=
