/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './comment.component';
const styles_CommentComponent:any[] = ([] as any[]);
export const RenderType_CommentComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_CommentComponent,
  data: {}
}
);
export function View_CommentComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
      (l()(),import0.ɵeld(0,(null as any),(null as any),10,'div',[[
        'class',
        'panel panel-default'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n  '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),1,'div',[[
        'class',
        'panel-body'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      '\n    ',
      '\n  '
    ]
    )),
    (l()(),import0.ɵted((null as any),['\n  '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),4,'div',[[
        'class',
        'panel-footer'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Submitted by  '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'b',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      '',
      ''
    ]
    )),
    (l()(),import0.ɵted((null as any),['\n  \n  '])),
    (l()(),import0.ɵted((null as any),['\n']))
  ]
  ,(null as any),(ck,v) => {
    var co:import1.CommentComponent = v.component;
    const currVal_0:any = co.comment.comment;
    ck(v,3,0,currVal_0);
    const currVal_1:any = co.comment.username;
    ck(v,8,0,currVal_1);
  });
}
function View_CommentComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-comment',([] as any[]),(null as any),(null as any),(null as any),View_CommentComponent_0,RenderType_CommentComponent)),
    import0.ɵdid(49152,(null as any),0,import1.CommentComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const CommentComponentNgFactory:import0.ComponentFactory<import1.CommentComponent> = import0.ɵccf('app-comment',import1.CommentComponent,View_CommentComponent_Host_0,{
  comment: 'comment',
  index: 'index'
}
,{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvTmlraGlsL0Rlc2t0b3AvQW5ndWxhckFwcHMveWVscGFwdC9hc3NldHMvYXBwL2NvbW1lbnRzL2NvbW1lbnQvY29tbWVudC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvTmlraGlsL0Rlc2t0b3AvQW5ndWxhckFwcHMveWVscGFwdC9hc3NldHMvYXBwL2NvbW1lbnRzL2NvbW1lbnQvY29tbWVudC5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9OaWtoaWwvRGVza3RvcC9Bbmd1bGFyQXBwcy95ZWxwYXB0L2Fzc2V0cy9hcHAvY29tbWVudHMvY29tbWVudC9jb21tZW50LmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvTmlraGlsL0Rlc2t0b3AvQW5ndWxhckFwcHMveWVscGFwdC9hc3NldHMvYXBwL2NvbW1lbnRzL2NvbW1lbnQvY29tbWVudC5jb21wb25lbnQudHMuQ29tbWVudENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9XCJwYW5lbCBwYW5lbC1kZWZhdWx0XCI+XHJcbiAgPGRpdiBjbGFzcz1cInBhbmVsLWJvZHlcIj5cclxuICAgIHt7Y29tbWVudC5jb21tZW50fX1cclxuICA8L2Rpdj5cclxuICA8ZGl2IGNsYXNzPVwicGFuZWwtZm9vdGVyXCI+U3VibWl0dGVkIGJ5ICA8Yj57e2NvbW1lbnQudXNlcm5hbWV9fTwvYj5cclxuICBcclxuICA8L2Rpdj5cclxuPC9kaXY+IiwiPGFwcC1jb21tZW50PjwvYXBwLWNvbW1lbnQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OztNQ0FBO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBaUM7TUFDL0I7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUF3QjtNQUFBO01BQUE7SUFBQTtJQUFBO0lBRWxCO01BQ047UUFBQTtRQUFBO01BQUE7SUFBQTtJQUEwQjtJQUFjO0lBQUc7TUFBQTtNQUFBO0lBQUE7SUFBQTtJQUF3QjtJQUU3RDs7OztJQUxrQjtJQUFBO0lBR21CO0lBQUE7Ozs7O0lDSjdDO2dCQUFBOzs7Ozs7OzsifQ==
